services:
  db:
    image: postgres:16
    container_name: ytasty-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ytasty_db
    ports:
      - '5432:5432'
        # La ou on va stocker notre bdd
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
# Docker créer et gérer cette espace de stockage
  postgres_data: